version: '3.8'
services:
  app:
    build:
      context: ./src/DockerAppDemo
      dockerfile_inline: |
        FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
        WORKDIR /App
        EXPOSE 7071
        COPY . ./
        RUN dotnet restore
        RUN dotnet publish -c Release -o out
        FROM mcr.microsoft.com/dotnet/aspnet:9.0
        WORKDIR /App
        COPY --from=build /App/out .
        RUN apt update && apt install -y wget && wget -O dotnet-dump https://aka.ms/dotnet-dump/linux-x64 && chmod +x dotnet-dump
        ENTRYPOINT ["./DockerAppDemo"]
    environment:
      ASPNETCORE_URLS: "https://+:7071"

      # 如果使用 https 要加以下這些 ref: https://learn.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-9.0
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "abc123"
    volumes:
      - ~/.aspnet/https:/https:ro

    ports:
      - '7071:7071'
