{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "obj size (over 10K)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "obj_size_bytes > 10000 AND obj_size_bytes{type!=\"Free\"}",
     "legendFormat": "{{type}} @ {{assembly}}"
    }
   ]
  },
  {
   "title": "obj count (over 256)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "obj_count > 256", "legendFormat": "{{type}} @ {{assembly}}" }
   ]
  },
  {
   "title": "obj size (app assembly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "obj_size_bytes{assembly=\"/App/DockerAppDemo.dll\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "obj count (app assembly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "obj_count{assembly=\"/App/DockerAppDemo.dll\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}